# Generated by Django 3.0.7 on 2020-06-05 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='project/')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('content', models.ManyToManyField(blank=True, related_name='content', to=settings.AUTH_USER_MODEL)),
                ('design', models.ManyToManyField(blank=True, related_name='design', to=settings.AUTH_USER_MODEL)),
                ('usability', models.ManyToManyField(blank=True, related_name='usability', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
