# Generated by Django 3.0.7 on 2020-06-06 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200606_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='content',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10, message='Range acceptable is 0-10'), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='votes',
            name='design',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10, message='Range acceptable is 0-10'), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='votes',
            name='usability',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10, message='Range acceptable is 0-10'), django.core.validators.MinValueValidator(0)]),
        ),
    ]
