# Generated by Django 3.0.7 on 2020-06-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='project/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(max_length=30),
        ),
    ]
